### ISSUE TITLE
Update docs to include manifest TOC control changes

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold-docs#52]
https://github.com/ManifoldScholar/manifold/pull/1863/commits/9aa02ce1443bdc54767e1a9127fc879a9f32ec28 

This adds the ability to structure manifest ingestions with a deeper TOC.  Users can link TOC items to hashes in the source file specified.

```
toc:
  - label: Title Set From TOC
    source_path: section_1.html
    start_section: true
    children:
      - label: Section 1.1
        source_path: section_1_1.html
      - label: First Anchor
        source_path: section_1_1.html#1
      - label: Second Anchor
        source_path: section_1_1.html#2
      - label: Third Anchor
        source_path: section_1_1.html#3
        children:
          - label: Section 1.1a
            source_path: section_1_1a.md
```
